# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.7/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ndymario/Desktop/Programming/Cpp/smb3-editor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ndymario/Desktop/Programming/Cpp/smb3-editor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ndymario/Desktop/Programming/Cpp/smb3-editor/CMakeFiles /Users/ndymario/Desktop/Programming/Cpp/smb3-editor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ndymario/Desktop/Programming/Cpp/smb3-editor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SMB3e

# Build rule for target.
SMB3e: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SMB3e
.PHONY : SMB3e

# fast build rule for target.
SMB3e/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SMB3e.dir/build.make CMakeFiles/SMB3e.dir/build
.PHONY : SMB3e/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

3rdparty/imgui/imgui.o: 3rdparty/imgui/imgui.cpp.o

.PHONY : 3rdparty/imgui/imgui.o

# target to build an object file
3rdparty/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui.cpp.o
.PHONY : 3rdparty/imgui/imgui.cpp.o

3rdparty/imgui/imgui.i: 3rdparty/imgui/imgui.cpp.i

.PHONY : 3rdparty/imgui/imgui.i

# target to preprocess a source file
3rdparty/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui.cpp.i
.PHONY : 3rdparty/imgui/imgui.cpp.i

3rdparty/imgui/imgui.s: 3rdparty/imgui/imgui.cpp.s

.PHONY : 3rdparty/imgui/imgui.s

# target to generate assembly for a file
3rdparty/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui.cpp.s
.PHONY : 3rdparty/imgui/imgui.cpp.s

3rdparty/imgui/imgui_demo.o: 3rdparty/imgui/imgui_demo.cpp.o

.PHONY : 3rdparty/imgui/imgui_demo.o

# target to build an object file
3rdparty/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_demo.cpp.o
.PHONY : 3rdparty/imgui/imgui_demo.cpp.o

3rdparty/imgui/imgui_demo.i: 3rdparty/imgui/imgui_demo.cpp.i

.PHONY : 3rdparty/imgui/imgui_demo.i

# target to preprocess a source file
3rdparty/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_demo.cpp.i
.PHONY : 3rdparty/imgui/imgui_demo.cpp.i

3rdparty/imgui/imgui_demo.s: 3rdparty/imgui/imgui_demo.cpp.s

.PHONY : 3rdparty/imgui/imgui_demo.s

# target to generate assembly for a file
3rdparty/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_demo.cpp.s
.PHONY : 3rdparty/imgui/imgui_demo.cpp.s

3rdparty/imgui/imgui_draw.o: 3rdparty/imgui/imgui_draw.cpp.o

.PHONY : 3rdparty/imgui/imgui_draw.o

# target to build an object file
3rdparty/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_draw.cpp.o
.PHONY : 3rdparty/imgui/imgui_draw.cpp.o

3rdparty/imgui/imgui_draw.i: 3rdparty/imgui/imgui_draw.cpp.i

.PHONY : 3rdparty/imgui/imgui_draw.i

# target to preprocess a source file
3rdparty/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_draw.cpp.i
.PHONY : 3rdparty/imgui/imgui_draw.cpp.i

3rdparty/imgui/imgui_draw.s: 3rdparty/imgui/imgui_draw.cpp.s

.PHONY : 3rdparty/imgui/imgui_draw.s

# target to generate assembly for a file
3rdparty/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_draw.cpp.s
.PHONY : 3rdparty/imgui/imgui_draw.cpp.s

3rdparty/imgui/imgui_impl_opengl2.o: 3rdparty/imgui/imgui_impl_opengl2.cpp.o

.PHONY : 3rdparty/imgui/imgui_impl_opengl2.o

# target to build an object file
3rdparty/imgui/imgui_impl_opengl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_impl_opengl2.cpp.o
.PHONY : 3rdparty/imgui/imgui_impl_opengl2.cpp.o

3rdparty/imgui/imgui_impl_opengl2.i: 3rdparty/imgui/imgui_impl_opengl2.cpp.i

.PHONY : 3rdparty/imgui/imgui_impl_opengl2.i

# target to preprocess a source file
3rdparty/imgui/imgui_impl_opengl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_impl_opengl2.cpp.i
.PHONY : 3rdparty/imgui/imgui_impl_opengl2.cpp.i

3rdparty/imgui/imgui_impl_opengl2.s: 3rdparty/imgui/imgui_impl_opengl2.cpp.s

.PHONY : 3rdparty/imgui/imgui_impl_opengl2.s

# target to generate assembly for a file
3rdparty/imgui/imgui_impl_opengl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_impl_opengl2.cpp.s
.PHONY : 3rdparty/imgui/imgui_impl_opengl2.cpp.s

3rdparty/imgui/imgui_impl_sdl.o: 3rdparty/imgui/imgui_impl_sdl.cpp.o

.PHONY : 3rdparty/imgui/imgui_impl_sdl.o

# target to build an object file
3rdparty/imgui/imgui_impl_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_impl_sdl.cpp.o
.PHONY : 3rdparty/imgui/imgui_impl_sdl.cpp.o

3rdparty/imgui/imgui_impl_sdl.i: 3rdparty/imgui/imgui_impl_sdl.cpp.i

.PHONY : 3rdparty/imgui/imgui_impl_sdl.i

# target to preprocess a source file
3rdparty/imgui/imgui_impl_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_impl_sdl.cpp.i
.PHONY : 3rdparty/imgui/imgui_impl_sdl.cpp.i

3rdparty/imgui/imgui_impl_sdl.s: 3rdparty/imgui/imgui_impl_sdl.cpp.s

.PHONY : 3rdparty/imgui/imgui_impl_sdl.s

# target to generate assembly for a file
3rdparty/imgui/imgui_impl_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_impl_sdl.cpp.s
.PHONY : 3rdparty/imgui/imgui_impl_sdl.cpp.s

3rdparty/imgui/imgui_widgets.o: 3rdparty/imgui/imgui_widgets.cpp.o

.PHONY : 3rdparty/imgui/imgui_widgets.o

# target to build an object file
3rdparty/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_widgets.cpp.o
.PHONY : 3rdparty/imgui/imgui_widgets.cpp.o

3rdparty/imgui/imgui_widgets.i: 3rdparty/imgui/imgui_widgets.cpp.i

.PHONY : 3rdparty/imgui/imgui_widgets.i

# target to preprocess a source file
3rdparty/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_widgets.cpp.i
.PHONY : 3rdparty/imgui/imgui_widgets.cpp.i

3rdparty/imgui/imgui_widgets.s: 3rdparty/imgui/imgui_widgets.cpp.s

.PHONY : 3rdparty/imgui/imgui_widgets.s

# target to generate assembly for a file
3rdparty/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/3rdparty/imgui/imgui_widgets.cpp.s
.PHONY : 3rdparty/imgui/imgui_widgets.cpp.s

src/levelParser.o: src/levelParser.cpp.o

.PHONY : src/levelParser.o

# target to build an object file
src/levelParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SMB3e.dir/build.make CMakeFiles/SMB3e.dir/src/levelParser.cpp.o
.PHONY : src/levelParser.cpp.o

src/levelParser.i: src/levelParser.cpp.i

.PHONY : src/levelParser.i

# target to preprocess a source file
src/levelParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SMB3e.dir/build.make CMakeFiles/SMB3e.dir/src/levelParser.cpp.i
.PHONY : src/levelParser.cpp.i

src/levelParser.s: src/levelParser.cpp.s

.PHONY : src/levelParser.s

# target to generate assembly for a file
src/levelParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SMB3e.dir/build.make CMakeFiles/SMB3e.dir/src/levelParser.cpp.s
.PHONY : src/levelParser.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SMB3e.dir/build.make CMakeFiles/SMB3e.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SMB3e.dir/build.make CMakeFiles/SMB3e.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SMB3e.dir/build.make CMakeFiles/SMB3e.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SMB3e"
	@echo "... imgui"
	@echo "... 3rdparty/imgui/imgui.o"
	@echo "... 3rdparty/imgui/imgui.i"
	@echo "... 3rdparty/imgui/imgui.s"
	@echo "... 3rdparty/imgui/imgui_demo.o"
	@echo "... 3rdparty/imgui/imgui_demo.i"
	@echo "... 3rdparty/imgui/imgui_demo.s"
	@echo "... 3rdparty/imgui/imgui_draw.o"
	@echo "... 3rdparty/imgui/imgui_draw.i"
	@echo "... 3rdparty/imgui/imgui_draw.s"
	@echo "... 3rdparty/imgui/imgui_impl_opengl2.o"
	@echo "... 3rdparty/imgui/imgui_impl_opengl2.i"
	@echo "... 3rdparty/imgui/imgui_impl_opengl2.s"
	@echo "... 3rdparty/imgui/imgui_impl_sdl.o"
	@echo "... 3rdparty/imgui/imgui_impl_sdl.i"
	@echo "... 3rdparty/imgui/imgui_impl_sdl.s"
	@echo "... 3rdparty/imgui/imgui_widgets.o"
	@echo "... 3rdparty/imgui/imgui_widgets.i"
	@echo "... 3rdparty/imgui/imgui_widgets.s"
	@echo "... src/levelParser.o"
	@echo "... src/levelParser.i"
	@echo "... src/levelParser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

